In [ ]:
import numpy as np
import pandas as pd
# Define the number of samples
num_samples = 10000
# Generate synthetic data for each feature
response_time = np.random.uniform(low=0, high=2, size=num_samples)  # Example for response time between 0 to 2 minutes
temperature = np.random.normal(loc=25, scale=5, size=num_samples)  # Example for temperature around 25 degrees Celsius
electricity_usage = np.random.uniform(low=0, high=100, size=num_samples)  # Example for electricity usage
humidity = np.random.uniform(low=20, high=80, size=num_samples)  # Example for humidity between 20% to 80%
motion_sensor = np.random.choice([0, 1], size=num_samples, p=[0.7, 0.3])  # Example for motion sensor on/off
led_actuator = np.random.choice([0, 1], size=num_samples, p=[0.5, 0.5])  # Example for LED actuator on/off
# Simulate labels based on conditions
labels = np.zeros(num_samples)
# Set labels to 1 based on conditions
labels[(response_time > 1) | (temperature > 30) | (electricity_usage > 80) | (humidity < 30) | (motion_sensor == 1)] = 1
# Create a DataFrame to store synthetic data
data = pd.DataFrame({
    'ResponseTime': response_time,
    'Temperature': temperature,
    'ElectricityUsage': electricity_usage,
    'Humidity': humidity,
    'MotionSensor': motion_sensor,
    'LEDActuator': led_actuator,
    'Label': labels
})
# Optionally, you can add noise or adjust distributions as needed

In [ ]:
data.head()

ResponseTime  Temperature  ElectricityUsage   Humidity  MotionSensor  \
0      0.796062    24.043570         48.820908  37.340889             0   
1      0.141424    24.708301         90.482654  53.514506             0   
2      0.718361    23.077981         57.359114  67.930698             0   
3      0.238684    32.924244         30.255107  26.837170             0   
4      1.560415    22.435796         28.763832  34.358565             0   

   LEDActuator  Label  
0            1    0.0  
1            0    1.0  
2            1    0.0  
3            0    1.0  
4            0    1.0

In [ ]:
data.to_csv('data.csv',index=False)

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X = data.drop('Label', axis=1)
y = data['Label']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)
# Predict on the test set
y_pred = model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("\nClassification Report:")
print(report)
print("\nConfusion Matrix:")
print(conf_matrix)

Accuracy: 0.9995

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       400
         1.0       1.00      1.00      1.00      1600

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000


Confusion Matrix:
[[ 400    0]
 [   1 1599]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)
# Predict on the test set
y_pred = model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("\nClassification Report:")
print(report)
print("\nConfusion Matrix:")
print(conf_matrix)

Accuracy: 0.999

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.99      1.00       400
         1.0       1.00      1.00      1.00      1600

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000


Confusion Matrix:
[[ 398    2]
 [   0 1600]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
k = 3  # Number of neighbors
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train, y_train)
# Predict on the test set
y_pred = model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("\nClassification Report:")
print(report)
print("\nConfusion Matrix:")
print(conf_matrix)

Accuracy: 0.7915

Classification Report:
              precision    recall  f1-score   support

         0.0       0.48      0.45      0.46       400
         1.0       0.86      0.88      0.87      1600

    accuracy                           0.79      2000
   macro avg       0.67      0.66      0.67      2000
weighted avg       0.79      0.79      0.79      2000


Confusion Matrix:
[[ 178  222]
 [ 195 1405]]


In [ ]:
# Train the AdaBoost model
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(random_state=42)
model.fit(X_train, y_train)
# Predict on the test set
y_pred = model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("\nClassification Report:")
print(report)
print("\nConfusion Matrix:")
print(conf_matrix)

Accuracy: 0.9995

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       400
         1.0       1.00      1.00      1.00      1600

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000


Confusion Matrix:
[[ 399    1]
 [   0 1600]]


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
# Train the Gradient Boosting model
model = GradientBoostingClassifier(random_state=42)
model.fit(X_train, y_train)
# Predict on the test set
y_pred = model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("\nClassification Report:")
print(report)
print("\nConfusion Matrix:")
print(conf_matrix)

Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       400
         1.0       1.00      1.00      1.00      1600

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000


Confusion Matrix:
[[ 400    0]
 [   0 1600]]


In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LeakyReLU

In [ ]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# Define the DNN model
model = Sequential()
# First hidden layer with 28 neurons and LeakyReLU activation
model.add(Dense(28, input_dim=X_train.shape[1]))
model.add(LeakyReLU(alpha=0.1))
# Second hidden layer with 14 neurons and ReLU activation
model.add(Dense(14, activation='relu'))
# Third hidden layer with 7 neurons and ReLU activation
model.add(Dense(7, activation='relu'))
# Fourth hidden layer with 3 neurons and ReLU activation
model.add(Dense(3, activation='relu'))
# Output layer with sigmoid activation
model.add(Dense(1, activation='sigmoid'))
# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=10, validation_split=0.2, verbose=1)
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
y_pred = (model.predict(X_test) > 0.5).astype("int32")
print(f"Test Accuracy: {accuracy}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/activations/leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(


Epoch 1/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8333 - loss: 0.4197 - val_accuracy: 0.9419 - val_loss: 0.1423
Epoch 2/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9354 - loss: 0.1431 - val_accuracy: 0.9594 - val_loss: 0.1061
Epoch 3/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9641 - loss: 0.0957 - val_accuracy: 0.9731 - val_loss: 0.0733
Epoch 4/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9710 - loss: 0.0735 - val_accuracy: 0.9744 - val_loss: 0.0601
Epoch 5/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9786 - loss: 0.0566 - val_accuracy: 0.9906 - val_loss: 0.0415
Epoch 6/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9833 - loss: 0.0425 - val_accuracy: 0.9825 - val_loss: 0.0420
Epoch 7/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9856 - loss: 0.0425 - val_accuracy: 0.9869 - val_loss: 0.0344
Epoch 8/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9858 - loss: 0.0359 - val_accu